name: build
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Build the Docker image
      run: |
        docker login --username=${{secrets.DOCKER_USERNAME}} --password=${{secrets.DOCKER_PASSWORD}} registry.cn-shanghai.aliyuncs.com
        docker build . --file Dockerfile --tag registry.cn-shanghai.aliyuncs.com/fifsky/caddy
        docker push registry.cn-shanghai.aliyuncs.com/fifsky/caddy

    - name: Pull docker and restart
      run: |
        curl "https://hook.fifsky.com/?token=${{secrets.WEBHOOK_TOKEN}}&script=caddy"

    - name: Dingtalk message
      uses: fifsky/dingtalk-action@master
      with:
        url: ${{ secrets.DINGTALK_WEBHOOK}}
        type: markdown
        content: |
          ## Github Action
          > caddy deploy successful
          > ^_^